"""Generate the QR module matrix for card.scad.

Writes qr_matrix.scad: the encoded URL, version and error level, plus every dark module as a
horizontal run [x, y, length] (row 0 is the top row of the symbol, quiet zone excluded).
card.scad refuses to render if its qr_url parameter does not match the URL in this file.

    .venv/bin/python scripts/gen_qr.py https://tbutman.com/hello
"""

import sys
from pathlib import Path

import segno

URL = sys.argv[1] if len(sys.argv) > 1 else "https://tbutman.com/hello"
ERROR = "m"  # version 2-M: 25 x 25 modules for this URL
OUT = Path(__file__).resolve().parent.parent / "qr_matrix.scad"

qr = segno.make(URL, error=ERROR, micro=False, boost_error=False)
rows = [list(row) for row in qr.matrix]
size = len(rows)

runs = []
for y, row in enumerate(rows):
    x = 0
    while x < size:
        if row[x]:
            start = x
            while x < size and row[x]:
                x += 1
            runs.append([start, y, x - start])
        else:
            x += 1

lines = [
    "// Generated by scripts/gen_qr.py. Do not edit by hand.",
    f'qr_matrix_url = "{URL}";',
    f'qr_matrix_designator = "{qr.designator}";',
    f"qr_matrix_size = {size};",
    "qr_matrix_runs = [",
    *(f"  [{x}, {y}, {n}]," for x, y, n in runs),
    "];",
    "",
]
OUT.write_text("\n".join(lines))
print(f"{URL} -> QR {qr.designator}, {size}x{size} modules, {len(runs)} runs -> {OUT.name}")
